// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA4r0ndnT3dUawxBXfTQ3M7EFeXXm9_MQ',
    appId: '1:313020968115:web:2616bb295952169f7914c6',
    messagingSenderId: '313020968115',
    projectId: 'ejercicio-examen-repaso',
    authDomain: 'ejercicio-examen-repaso.firebaseapp.com',
    storageBucket: 'ejercicio-examen-repaso.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH6WIoqcG2vAkwzCPiajM-p8BllyFEJo0',
    appId: '1:313020968115:android:5dfe71a97452d0f77914c6',
    messagingSenderId: '313020968115',
    projectId: 'ejercicio-examen-repaso',
    storageBucket: 'ejercicio-examen-repaso.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkPKGey8W6SInjD1pSMwByMfxGM8zN_ig',
    appId: '1:313020968115:ios:ade788977bb606817914c6',
    messagingSenderId: '313020968115',
    projectId: 'ejercicio-examen-repaso',
    storageBucket: 'ejercicio-examen-repaso.firebasestorage.app',
    iosBundleId: 'com.example.pmdmEjercicioExamen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkPKGey8W6SInjD1pSMwByMfxGM8zN_ig',
    appId: '1:313020968115:ios:ade788977bb606817914c6',
    messagingSenderId: '313020968115',
    projectId: 'ejercicio-examen-repaso',
    storageBucket: 'ejercicio-examen-repaso.firebasestorage.app',
    iosBundleId: 'com.example.pmdmEjercicioExamen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA4r0ndnT3dUawxBXfTQ3M7EFeXXm9_MQ',
    appId: '1:313020968115:web:3b7ef4ac046639457914c6',
    messagingSenderId: '313020968115',
    projectId: 'ejercicio-examen-repaso',
    authDomain: 'ejercicio-examen-repaso.firebaseapp.com',
    storageBucket: 'ejercicio-examen-repaso.firebasestorage.app',
  );
}
